# Site Settings
title: PBS Jekyll Demo Site

# Build Settings
plugins:
  - jekyll-autoprefixer

# Settings for the autoprefixer plugin
autoprefixer:
  browsers:
    - last 4 versions
    - Safari > 2

# Set the site-wide SEO and OpenGraph metadata
meta:
  author: Bart Busschots
  locale: en_IE
  og_type: website
  og_image: assets/siteIllustration.png

# Define site collections
collections:
  socialmedia_profiles:
    output: false
    sort_by: sort_order